
export const CourseListData = {
    A: [
        'Accountancy (ACCT)',
        'Africana Studies (AFRS)',
        'Am Sign Lang Ling&Deaf Culture (ASLD)',
        'American Indian Studies (AIS)',
        'American Studies (AMST)',
        'Anthropology (ANTH)',
        'Arabic (ARAB)',
        'Art (ART)',
        'Art History (AH)',
        'Asian & Asian American Studies (AAAS)',
        'Asian American Studies (ASAM)',
        'Asian Studies (A/ST)',
        'Astronomy (ASTR)',
        'Athletic Training (AT)',
        'Athletics (ATHL)',
    ],
    B: [
        'Biology (BIOL)',
        'Biomedical Engineering (BME)',
        'Business Law (BLAW)',
        'Business, College of (CBA)',
    ],
    C: [
        'CSU OnLine - LB ONLY (OLNE)',
        'Cambodian (KHMR)',
        'Chemical Engineering (CH E)',
        'Chemistry & Biochemistry (CHEM)',
        'Chicano & Latino Studies (CHLS)',
        'Child Developmnt & Family Stds (CDFS)',
        'Chinese (CHIN)',
        'Civil Engineering (C E)',
        'Classics (CLSC)',
        'College of the Arts (COTA)',
        'Communication Studies (COMM)',
        'Comparative World Literature (CWL)',
        'Computer Engr & Computer Sci (CECS)',
        'Concurrent Enrollment (XYZ)',
        'Construction Engineering Mgmt (CEM)',
        'Consumer Affairs (CAFF)',
        'Counseling (COUN)',
        'Criminology & Criminal Justice (CRJU)',
        'Cross Enroll Place Holder (XENR)',
    ],
    D: [
        'Dance (DANC)',
        'Design (DESN)',
        'Doctor of Physical Therapy (DPT)',
    ],
    E: [
        'Earth Science (ERTH)',
        'Economics (ECON)',
        'Educ Leadership Doctorate (EDLD)',
        'Education - Curr & Instruction (EDCI)',
        'Education - Early Childhood (EDEC)',
        'Education - Elementary (EDEL)',
        'Education - Reading (EDRG)',
        'Education - Secondary (EDSE)',
        'Education - Single Subject (EDSS)',
        'Education Specialist (EDSP)',
        'Educational Administration (EDAD)',
        'Educational Opportunity Prog (EOP)',
        'Educational Psychology (ED P)',
        'Educational Technology (ETEC)',
        'Electrical Engineering (E E)',
        'Emergency Services Adm (EMER)',
        'Engineering (ENGR)',
        'Engineering Technology (E T)',
        'English (ENGL)',
        'Enrollment Services (ES)',
        'Environmental Science & Policy (ES P)',
        'Equity, Educ, & Social Justice (EESJ)',
    ],
    F: [
        'Fashion Merchandising & Design (FMD)',
        'Filipino (FIL)',
        'Film and Electronic Arts (FEA)',
        'Finance (FIN)',
        'Food Science (FSCI)',
        'French (FREN)',
    ],
    G: [
        'Geography (GEOG)',
        'German (GERM)',
        'Gerontology (GERN)',
        'Graduate Business Admin (GBA)',
        'Greek (GK)',
    ],
    H: [
        'Health Care Administration (HCA)',
        'Health Science (H SC)',
        'Hebrew (HEBW)',
        'Hindi-Urdu (HIND)',
        'History (HIST)',
        'Hospitality Management (HM)',
        'Human Development (HDEV)',
        'Human Resources Management (HRM)',
    ],
    I: [
        'Information Systems (I S)',
        'International Education (INTL)',
        'International Studies (I/ST)',
        'Italian (ITAL)',
    ],
    J: [
        'Japanese (JAPN)',
        'Journalism (JOUR)',
    ],
    K: [
        'Kinesiology (KIN)',
        'Korean (KOR)',
    ],
    L: [
        'Latin (LAT)',
        'Liberal Arts, College of (C/LA)',
        'Liberal Studies (L/ST)',
        'Linguistics (LING)',
    ],
    M: [
        'Management (MGMT)',
        'Marketing (MKTG)',
        'Mathematics (MATH)',
        'Mathematics Education (MTED)',
        'Mechanical & Aerospace Engr (MAE)',
        'Military Science (M S)',
        'Music (MUS)',
    ],
    N: [
        'Natural Sciences (NSCI)',
        'Nursing (NRSG)',
        'Nutrition and Dietetics (NUTR)',
    ],
    O: [
        'Ocean Studies Institute (OSI)',
    ],
    P: [
        'Philosophy (PHIL)',
        'Physical Science (PHSC)',
        'Physics (PHYS)',
        'Political Science (POSC)',
        'Psychology (PSY)',
        'Public Policy & Administration (PPA)',
    ],
    R: [
        'Recreation (REC)',
        'Religious Studies (R/ST)',
        'Romance German Russian Lang (RGR)',
        'Russian (RUSS)',
    ],
    S: [
        'Science Education (SCED)',
        'Social Work (S W)',
        'Sociology (SOC)',
        'Spanish (SPAN)',
        'Speech-Language-Pathology (SLP)',
        'Statistics (STAT)',
        'Student Development Higher ED (SDHE)',
        'Student Rec & Leadership (SRL)',
        'Supplemental Instruction (S/I)',
        'Supply Chain Management (SCM)',
    ],
    T: [
        'Theatre Arts (THEA)',
        'Translation Studies (TRST)',
    ],
    U: [
        'University (UNIV)',
        'University Honors Program (UHP)',
        'Urban Dual Credential Program (UDCP)',
    ],
    V: [
        'Vietnamese (VIET)',
    ],
    W: [
        "Women's Gender Sexuality Stds (WGSS)",
    ],
};
