
export const ProfessorReviewData = {
    "Comments": [
        {
            "Attendance": "Not Mandatory",
            "Comment": "The only homework was a few programming projects that can be finished in a few hours. The programming assignments cover a wild variety of things. One of them focused on maxheap and all are different programming language, some very old languages. He can go on tangents that help us more than material, but quizzes seem to be from the textbook.",
            "Course": "CECS325",
            "Date": "May 25th, 2023",
            "Difficulty": "3.0",
            "ForCredit": "Yes",
            "Grade": "A",
            "Quality": "4.0",
            "TakeAgain": "Yes",
            "Textbook": "Yes"
        },
        {
            "Attendance": "Not Mandatory",
            "Comment": "I recommend learning the basics of C++ before taking this course. Coding assignments and quizzes are based on previous assignments, so make sure you understand how your programs work behind the scenes. No lecture slides, Gold just shows up and starts teaching. Classes felt more like a conversation rather than a lecture, which was cool.",
            "Course": "CECS325",
            "Date": "May 18th, 2023",
            "Difficulty": "3.0",
            "ForCredit": "Yes",
            "Grade": "A",
            "Quality": "5.0",
            "TakeAgain": "Yes",
            "Textbook": "N/A"
        },
        {
            "Attendance": "Not Mandatory",
            "Comment": "Cool professor but lectures are freestyle which make material hard to understand. Quiz and test are not bad.",
            "Course": "CECS325",
            "Date": "May 12th, 2023",
            "Difficulty": "3.0",
            "ForCredit": "Yes",
            "Grade": "C+",
            "Quality": "4.0",
            "TakeAgain": "N/A",
            "Textbook": "N/A"
        },
        {
            "Attendance": "Not Mandatory",
            "Comment": "Lectures really aren't useful if you already understand C++. There isn't much Linux after the first month either. His quizzes don't really align with the lectures sometimes and the programming assignments can be done quite easily. However, he will dock your grade for any minor mistakes made on those assignments. Super cool guy who cares though.",
            "Course": "CECS325",
            "Date": "May 7th, 2023",
            "Difficulty": "1.0",
            "ForCredit": "Yes",
            "Grade": "A",
            "Quality": "4.0",
            "TakeAgain": "N/A",
            "Textbook": "N/A"
        },
        {
            "Attendance": "Not Mandatory",
            "Comment": "Definitely a great professor who enjoys teaching his teach very much.",
            "Course": "CECS282",
            "Date": "May 17th, 2022",
            "Difficulty": "1.0",
            "ForCredit": "Yes",
            "Grade": "N/A",
            "Quality": "5.0",
            "TakeAgain": "Yes",
            "Textbook": "Yes"
        },
        {
            "Attendance": "Not Mandatory",
            "Comment": "Don't confuse professor Gold for Goldstein. They are the OPPOSITE! Professor Gold's lectures were very informative and helped immensely on each coding project he had provided. Quizzes and exams were a bit difficult for me which is why I got a B, but not once did I study and got the majority of the info from his lectures alone.",
            "Course": "CECS282",
            "Date": "Jan 21st, 2022",
            "Difficulty": "2.0",
            "ForCredit": "Yes",
            "Grade": "B+",
            "Quality": "4.0",
            "TakeAgain": "Yes",
            "Textbook": "Yes"
        },
        {
            "Attendance": "Not Mandatory",
            "Comment": "Funny guy, chill, and laidback. Class is graded based on 6 projects, 6 quizzes, 2 exams, and a lab section. Projects aren't too difficult, but the last 2 require more time. Quizzes and exams weren't too bad either. Lab is group work. Lectures were actually pretty entertaining, concise, and informative. Overall, great professor, easy A/B",
            "Course": "CECS282",
            "Date": "Dec 19th, 2021",
            "Difficulty": "2.0",
            "ForCredit": "Yes",
            "Grade": "A",
            "Quality": "5.0",
            "TakeAgain": "Yes",
            "Textbook": "No"
        },
        {
            "Attendance": "Not Mandatory",
            "Comment": "Professor Gold is an amazing and caring guy. He explains concepts so well and is so funny. Apart from some tough quizzes, his projects are nothing too hard and exams aren't bad either. Do well enough and he might even let you skip the final. If you are ever confused don't hesitate to ask questions, he will help!",
            "Course": "CECS282",
            "Date": "May 18th, 2021",
            "Difficulty": "1.0",
            "ForCredit": "Yes",
            "Grade": "A",
            "Quality": "5.0",
            "TakeAgain": "Yes",
            "Textbook": "No"
        },
        {
            "Attendance": "Mandatory",
            "Comment": "Professor Gold is very approachable and gives great lectures to follow. His grading criteria sometimes isnt the clearest, but his teachings and enthusiasm makes up for it completely. Highly recommend him for anyone wanting to learn and enjoy in doing so.",
            "Course": "CECS282",
            "Date": "May 14th, 2021",
            "Difficulty": "3.0",
            "ForCredit": "Yes",
            "Grade": "N/A",
            "Quality": "4.0",
            "TakeAgain": "Yes",
            "Textbook": "No"
        },
        {
            "Attendance": "Not Mandatory",
            "Comment": "His projects are very clear, he explains everything well, and his lectures are engaging. I felt like I was actually learning C++ and having fun. Other CS professors I've had at this school feel like they're actively trying to prevent you from learning but that is not the case here. I would recommend.",
            "Course": "CECS282",
            "Date": "May 5th, 2021",
            "Difficulty": "3.0",
            "ForCredit": "Yes",
            "Grade": "B",
            "Quality": "5.0",
            "TakeAgain": "Yes",
            "Textbook": "No"
        },
        {
            "Attendance": "N/A",
            "Comment": "He's really good at posting recorded lectures. He's a really nice guy who genuinely wants his students to do good in his class. I really enjoyed his class. I'm taking him again for C++. You'll be totally fine if you do all your assignments on time. His demos for projects are just screenshots of your code output.",
            "Course": "CECS274",
            "Date": "Feb 19th, 2021",
            "Difficulty": "2.0",
            "ForCredit": "Yes",
            "Grade": "N/A",
            "Quality": "5.0",
            "TakeAgain": "Yes",
            "Textbook": "No"
        },
        {
            "Attendance": "Not Mandatory",
            "Comment": "Pretty good lecturer and tries his best to answer students' questions. Easy class if you just do your projects on time. Quizzes and exam are really easy too.",
            "Course": "CECS274",
            "Date": "Dec 19th, 2020",
            "Difficulty": "3.0",
            "ForCredit": "Yes",
            "Grade": "Not sure yet",
            "Quality": "5.0",
            "TakeAgain": "Yes",
            "Textbook": "No"
        },
        {
            "Attendance": "N/A",
            "Comment": "Only take Gold for 277 if you're willing to put in the work to learn. He does a good job teaching during the lectures, but for the actual assignments, you are pretty much on your own. If you put in the work needed, you will learn a ton. For the 6 quizzes and 2 tests, there was nothing on them you wouldn't learn just from doing the work assigned.",
            "Course": "CECS277",
            "Date": "Dec 10th, 2020",
            "Difficulty": "4.0",
            "ForCredit": "Yes",
            "Grade": "Not sure yet",
            "Quality": "4.0",
            "TakeAgain": "Yes",
            "Textbook": "No"
        },
        {
            "Attendance": "Not Mandatory",
            "Comment": "This was my first c++ class and was fairly easy. Gold is a really good professor and he actually cares about what he's teaching as well as his students. The homework assignments aren't too hard and he pretty much teaches you everything you need to know for them in class. Midterms/Quizzes are mostly easy.",
            "Course": "CECS282",
            "Date": "Jun 6th, 2020",
            "Difficulty": "2.0",
            "ForCredit": "Yes",
            "Grade": "A",
            "Quality": "5.0",
            "TakeAgain": "Yes",
            "Textbook": "No"
        },
        {
            "Attendance": "Not Mandatory",
            "Comment": "If you don't take Gold for 274 you're actually making the biggest mistake of your life.",
            "Course": "CECS274",
            "Date": "Jan 8th, 2020",
            "Difficulty": "2.0",
            "ForCredit": "N/A",
            "Grade": "A",
            "Quality": "5.0",
            "TakeAgain": "Yes",
            "Textbook": "No"
        },
        {
            "Attendance": "Not Mandatory",
            "Comment": "Great guy and great professor; quiz after every program, 1 midterm 1 final, study for exams using previous quizzes as your guide bc the questions will likely be the quizzes, can opt out on final if satisfied w/ current grade, in class participation is encouraged. Choose this professor, you'll thank me later.",
            "Course": "CECS274",
            "Date": "Dec 18th, 2019",
            "Difficulty": "3.0",
            "ForCredit": "Yes",
            "Grade": "A",
            "Quality": "5.0",
            "TakeAgain": "Yes",
            "Textbook": "No"
        },
        {
            "Attendance": "Not Mandatory",
            "Comment": "This class is not that bad until you hit BigInts. BigInts will be the hardest project in the class. Stsrt early. Also, do not take this class with PHYS 152 at the same time. Second, C++ is a lot harder than expected. You may have to review C++ again for 326, 328, 424. If you follow lectures, and projects, then midterm and final should be ok.",
            "Course": "CECS282",
            "Date": "Jun 15th, 2019",
            "Difficulty": "4.0",
            "ForCredit": "Yes",
            "Grade": "C",
            "Quality": "5.0",
            "TakeAgain": "Yes",
            "Textbook": "No"
        },
        {
            "Attendance": "Not Mandatory",
            "Comment": "Overall a good professor. The only problem is he does not give notes in the class and his lectures are all based on the lab assignments which he gives.",
            "Course": "CECS282",
            "Date": "Mar 2nd, 2019",
            "Difficulty": "3.0",
            "ForCredit": "Yes",
            "Grade": "N/A",
            "Quality": "4.0",
            "TakeAgain": "No",
            "Textbook": "No"
        },
        {
            "Attendance": "Mandatory",
            "Comment": "He crakes jokes 24/7 and encourages students to learn C++ to be the main language! Quizzes are based on the projects, so make sure you do THEM! Blizzard and gaming companies heavily rely on C++! Don't freak out because Master Gold is willing to guide you to understand the concepts at anytime! Can't wait to join the programming team next fall!",
            "Course": "CECS282",
            "Date": "Feb 22nd, 2019",
            "Difficulty": "4.0",
            "ForCredit": "Yes",
            "Grade": "Not sure yet",
            "Quality": "5.0",
            "TakeAgain": "Yes",
            "Textbook": "No"
        },
        {
            "Attendance": "Mandatory",
            "Comment": "Well, this class atm is pretty cool rn. He crakes jokes 24/7 and references real life situations to have students really learn C++ the best way as possible. The most challenging part of C++ is the projects. The quizzes are based on the projects, so make sure you do THEM! C++ is main program of industries! Can't wait to join the programming team!!!!",
            "Course": "CECS282",
            "Date": "Feb 22nd, 2019",
            "Difficulty": "4.0",
            "ForCredit": "Yes",
            "Grade": "Not sure yet",
            "Quality": "5.0",
            "TakeAgain": "Yes",
            "Textbook": "No"
        }
    ],
    "ProfID": 307547,
    "avgDifficulty": 2.5,
    "avgRating": 4.5,
    "department": "Computer Science",
    "firstName": "Steve",
    "lastName": "Gold",
    "numRatings": 51,
    "school": "U2Nob29sLTE4ODQ2",
    "wouldTakeAgain": 89.2857
}